library("dplyr")
library("survival")

# Load bootstrap HR summary
# This file is generated by bootstrap_noreplace.R
output_dir <- "bootstrap_results"  # Update this to match your bootstrap output directory
hr_summary_file <- file.path(output_dir, "bootstrap_summary.csv")

if (!file.exists(hr_summary_file)) {
  stop(sprintf("HR summary file not found: %s\nPlease run bootstrap_noreplace.R first.", hr_summary_file))
}

hr_bootstrap <- read.csv(hr_summary_file)

# Check if outcomes_df.long exists (should be created by find_kZ_script.R)
# If not, try to source weights_script.R which should have it
if (!exists("outcomes_df.long")) {
  # Try to source weights_script.R to get the point estimate models
  # Note: This assumes find_kZ_script.R has been run first
  if (file.exists("weights_script.R")) {
    source("weights_script.R")
  } else {
    stop("outcomes_df.long not found in environment and weights_script.R not found.\nPlease run find_kZ_script.R and weights_script.R first.")
  }
}

# Get point estimate HR from weights_script.R models
# Cox models return coefficients which are log(HR)
# We need to extract these and transform to HR scale

# UNADJUSTED
if (!exists("fit_unadjusted")) {
  fit_unadjusted <- coxph(Surv(Tstart, time, ami) ~ treatment, 
                          data = outcomes_df.long, 
                          id = rowId)
}
unadj_logHR <- coef(fit_unadjusted)
unadj_HR <- exp(unadj_logHR)

# IPCW STABILIZED TRUNCATED
if (!exists("fit_ipcw_Stab_trunc")) {
  fit_ipcw_Stab_trunc <- coxph(Surv(Tstart, time, ami) ~ treatment, 
                               data = outcomes_df.long, 
                               id = rowId, 
                               weights = Stab_ipcw_trunc)
}
ipcw_logHR <- coef(fit_ipcw_Stab_trunc)
ipcw_HR <- exp(ipcw_logHR)

# IPTW TRUNCATED
if (!exists("fit_iptw_trunc")) {
  fit_iptw_trunc <- coxph(Surv(Tstart, time, ami) ~ treatment, 
                         data = outcomes_df.long, 
                         id = rowId, 
                         weights = iptw_trunc)
}
iptw_logHR <- coef(fit_iptw_trunc)
iptw_HR <- exp(iptw_logHR)

# COMBINED
if (!exists("fit_comb")) {
  fit_comb <- coxph(Surv(Tstart, time, ami) ~ treatment, 
                    data = outcomes_df.long, 
                    id = rowId, 
                    weights = comb)
}
comb_logHR <- coef(fit_comb)
comb_HR <- exp(comb_logHR)

# Create point estimate data
# Note: Bootstrap uses model names: "unadjusted", "ipcw_stab_trunc", "iptw_trunc", "combined"
point_estimates <- list(
  unadjusted = list(logHR = unadj_logHR, HR = unadj_HR),
  ipcw_stab_trunc = list(logHR = ipcw_logHR, HR = ipcw_HR),
  iptw_trunc = list(logHR = iptw_logHR, HR = iptw_HR),
  combined = list(logHR = comb_logHR, HR = comb_HR)
)

# Match bootstrap results with point estimates by Model name
# Replace bootstrap means with point estimates, keep bootstrap CIs
hr_df <- hr_bootstrap %>%
  mutate(
    # Log(HR) scale - replace bootstrap mean with point estimate
    logHR_estimate = case_when(
      Model == "unadjusted" ~ point_estimates$unadjusted$logHR,
      Model == "ipcw_stab_trunc" ~ point_estimates$ipcw_stab_trunc$logHR,
      Model == "iptw_trunc" ~ point_estimates$iptw_trunc$logHR,
      Model == "combined" ~ point_estimates$combined$logHR,
      TRUE ~ NA_real_
    ),
    # HR scale - replace bootstrap mean with point estimate
    HR_estimate = case_when(
      Model == "unadjusted" ~ point_estimates$unadjusted$HR,
      Model == "ipcw_stab_trunc" ~ point_estimates$ipcw_stab_trunc$HR,
      Model == "iptw_trunc" ~ point_estimates$iptw_trunc$HR,
      Model == "combined" ~ point_estimates$combined$HR,
      TRUE ~ NA_real_
    )
  ) %>%
  # Reorder columns for clarity: keep bootstrap CIs, remove _mean columns
  select(Model, 
         logHR_estimate, logHR_CI_lower, logHR_CI_upper,
         HR_estimate, HR_CI_lower, HR_CI_upper,
         n_valid)

# Print the dataframe
cat("\n=== HR Results: Point Estimates with Bootstrap Confidence Intervals ===\n")
cat("Note: HR = exp(logHR), where logHR is the coefficient from Cox model\n")
cat("      HR > 1 means Thiazide has higher hazard than ACEi\n")
cat("      HR < 1 means Thiazide has lower hazard than ACEi\n\n")
print(hr_df)

# Save to CSV
output_file <- "hr_point_est_with_bootstrap_ci.csv"
write.csv(hr_df, output_file, row.names = FALSE)
cat(sprintf("\nHR results saved to: %s\n", output_file))

# Also create a more formatted version for presentation
hr_formatted <- hr_df %>%
  mutate(
    logHR = sprintf("%.3f (%.3f, %.3f)", logHR_estimate, logHR_CI_lower, logHR_CI_upper),
    HR = sprintf("%.3f (%.3f, %.3f)", HR_estimate, HR_CI_lower, HR_CI_upper)
  ) %>%
  select(Model, logHR, HR, n_valid)

cat("\n=== Formatted HR Results ===\n")
print(hr_formatted)

formatted_file <- "hr_point_est_with_bootstrap_ci_formatted.csv"
write.csv(hr_formatted, formatted_file, row.names = FALSE)
cat(sprintf("Formatted HR results saved to: %s\n", formatted_file))

# Also create a version with cleaner model names for presentation
hr_clean_names <- hr_df %>%
  mutate(
    Model_clean = case_when(
      Model == "unadjusted" ~ "Unadjusted",
      Model == "ipcw_stab_trunc" ~ "IPCW",
      Model == "iptw_trunc" ~ "IPTW",
      Model == "combined" ~ "Combined (IPTW + IPCW)",
      TRUE ~ Model
    ),
    logHR = sprintf("%.3f (%.3f, %.3f)", logHR_estimate, logHR_CI_lower, logHR_CI_upper),
    HR = sprintf("%.3f (%.3f, %.3f)", HR_estimate, HR_CI_lower, HR_CI_upper)
  ) %>%
  select(Model_clean, logHR, HR, n_valid)

cat("\n=== HR Results with Clean Model Names ===\n")
print(hr_clean_names)

clean_names_file <- "hr_point_est_with_bootstrap_ci_clean_names.csv"
write.csv(hr_clean_names, clean_names_file, row.names = FALSE)
cat(sprintf("HR results with clean names saved to: %s\n", clean_names_file))

cat("\nDone!\n")
