library("ggplot2")
library("dplyr")
library("survival")

# Load bootstrap survival curves summary
# This file is generated by bootstrap_noreplace.R
output_dir <- "bootstrap_results"  # Update this to match your bootstrap output directory
survcurves_summary_file <- file.path(output_dir, "bootstrap_survival_curves_summary.csv")

if (!file.exists(survcurves_summary_file)) {
  stop(sprintf("Survival curves summary file not found: %s\nPlease run bootstrap_noreplace.R first.", survcurves_summary_file))
}

surv_summary <- read.csv(survcurves_summary_file)

# Extract time grid from bootstrap summary (should match bootstrap_noreplace.R)
time_grid <- sort(unique(surv_summary$time))
tau <- max(time_grid)

# Helper function to extract survival curve at specific time points
# (matches the function from bootstrap_noreplace.R)
extract_survival_curve <- function(survfit_obj, time_points) {
  tryCatch({
    surv_summary <- summary(survfit_obj, times = time_points, extend = TRUE)
    
    # Identify strata
    strata_names <- unique(surv_summary$strata)
    if (length(strata_names) != 2) {
      return(data.frame(time = time_points, surv0 = NA, surv1 = NA))
    }
    
    # Extract survival for each treatment group
    # Handle different possible strata naming conventions (treatment=0, Thiazide=0, etc.)
    extract_group_surv <- function(value_pattern) {
      # Find strata matching the pattern (e.g., "=0" or "=1")
      matching_strata <- grep(value_pattern, strata_names, value = TRUE)
      if (length(matching_strata) == 0) {
        return(rep(NA, length(time_points)))
      }
      idx <- which(surv_summary$strata == matching_strata[1])
      time <- surv_summary$time[idx]
      surv <- surv_summary$surv[idx]
      # Interpolate/extend to match time_points
      surv_interp <- approx(time, surv, xout = time_points, method = "constant", 
                           yleft = 1, yright = tail(surv, 1), rule = 2)$y
      return(surv_interp)
    }
    
    # Try to extract by value (treatment=0 and treatment=1)
    surv0 <- extract_group_surv("=0")
    surv1 <- extract_group_surv("=1")
    
    # If extraction failed, use strata order (first = treatment 0, second = treatment 1)
    if (all(is.na(surv0)) || all(is.na(surv1))) {
      ordered_strata <- unique(surv_summary$strata)
      if (length(ordered_strata) == 2) {
        idx0 <- which(surv_summary$strata == ordered_strata[1])
        idx1 <- which(surv_summary$strata == ordered_strata[2])
        time0 <- surv_summary$time[idx0]
        surv0_vals <- surv_summary$surv[idx0]
        time1 <- surv_summary$time[idx1]
        surv1_vals <- surv_summary$surv[idx1]
        surv0 <- approx(time0, surv0_vals, xout = time_points, method = "constant", 
                       yleft = 1, yright = tail(surv0_vals, 1), rule = 2)$y
        surv1 <- approx(time1, surv1_vals, xout = time_points, method = "constant", 
                       yleft = 1, yright = tail(surv1_vals, 1), rule = 2)$y
      }
    }
    
    return(data.frame(time = time_points, surv0 = surv0, surv1 = surv1))
  }, error = function(e) {
    return(data.frame(time = time_points, surv0 = NA, surv1 = NA))
  })
}

# Check if outcomes_df.long exists (should be created by find_kZ_script.R)
# If not, try to source weights_script.R which should have it
if (!exists("outcomes_df.long")) {
  # Try to source weights_script.R to get the point estimate models
  # Note: This assumes find_kZ_script.R has been run first
  if (file.exists("weights_script.R")) {
    source("weights_script.R")
  } else {
    stop("outcomes_df.long not found in environment and weights_script.R not found.\nPlease run find_kZ_script.R and weights_script.R first.")
  }
}

# Get point estimate survival curves from weights_script.R models
# These will replace the bootstrap means in the plot

# UNADJUSTED
unadj_fit <- survfit(Surv(Tstart, time, ami) ~ treatment, 
                     data = outcomes_df.long, 
                     id = rowId)
unadj_point_est <- extract_survival_curve(unadj_fit, time_grid)

# IPTW
iptw_fit <- survfit(Surv(Tstart, time, ami) ~ treatment, 
                    data = outcomes_df.long, 
                    id = rowId, 
                    weights = iptw_trunc)
iptw_point_est <- extract_survival_curve(iptw_fit, time_grid)

# IPCW (using Stab_ipcw_trunc as in weights_script.R)
ipcw_fit <- survfit(Surv(Tstart, time, ami) ~ treatment, 
                    data = outcomes_df.long, 
                    id = rowId, 
                    weights = Stab_ipcw_trunc)
ipcw_point_est <- extract_survival_curve(ipcw_fit, time_grid)

# COMBINED
comb_fit <- survfit(Surv(Tstart, time, ami) ~ treatment, 
                    data = outcomes_df.long, 
                    id = rowId, 
                    weights = comb)
comb_point_est <- extract_survival_curve(comb_fit, time_grid)

# Replace bootstrap means with point estimates, keeping bootstrap CIs
surv_summary <- surv_summary %>%
  left_join(
    bind_rows(
      unadj_point_est %>% mutate(model = "unadjusted"),
      iptw_point_est %>% mutate(model = "iptw"),
      ipcw_point_est %>% mutate(model = "ipcw"),
      comb_point_est %>% mutate(model = "combined")
    ),
    by = c("model", "time")
  ) %>%
  mutate(
    surv0_mean = surv0,  # Replace bootstrap mean with point estimate
    surv1_mean = surv1   # Replace bootstrap mean with point estimate
  ) %>%
  select(-surv0, -surv1)  # Remove temporary columns

# Theme matching the original plot style
big_axis <- theme(
  axis.title = element_text(size = 34),
  axis.text  = element_text(size = 22),
  legend.title = element_text(size = 22),
  legend.text  = element_text(size = 22)
)

# Function to create survival curve plot with bootstrap CIs
# Matches the style of plot_survival_curves_final_clean.R
create_survival_plot <- function(data, model_name, title = NULL) {
  # Prepare data for plotting
  # We need to create separate rows for treatment 0 (ACEi) and treatment 1 (Thiazide)
  plot_data <- bind_rows(
    data %>%
      select(time, surv = surv0_mean, ci_lower = surv0_CI_lower, ci_upper = surv0_CI_upper) %>%
      mutate(Treatment = "ACEi"),
    data %>%
      select(time, surv = surv1_mean, ci_lower = surv1_CI_lower, ci_upper = surv1_CI_upper) %>%
      mutate(Treatment = "Thiazide")
  )
  
  # Create the plot matching ggsurvplot style
  # Using default ggplot2 colors (similar to ggsurvplot defaults)
  p <- ggplot(plot_data, aes(x = time, y = surv, color = Treatment, linetype = Treatment)) +
    geom_line(size = 1.2) +
    geom_ribbon(aes(ymin = ci_lower, ymax = ci_upper, fill = Treatment), 
                alpha = 0.2, linetype = 0, show.legend = FALSE) +
    scale_color_manual(values = c("ACEi" = "#E7B800", "Thiazide" = "#2E9FDF"),
                      labels = c("ACEi", "Thiazide")) +
    scale_fill_manual(values = c("ACEi" = "#E7B800", "Thiazide" = "#2E9FDF"),
                     guide = "none") +
    scale_linetype_manual(values = c("ACEi" = "solid", "Thiazide" = "dashed"),
                         labels = c("ACEi", "Thiazide")) +
    labs(x = "Time (days)", 
         y = "Survival Probability",
         color = "Treatment",
         linetype = "Treatment") +
    theme_bw() + 
    big_axis +
    theme(legend.position = "bottom",
          legend.direction = "horizontal",
          legend.box = "horizontal") +
    ylim(0.85, 1) +
    xlim(0, max(plot_data$time, na.rm = TRUE))
  
  return(p)
}

# Create plots for each model (matching the order in plot_survival_curves_final_clean.R)

# NO ADJUSTMENT
unadj_data <- surv_summary %>%
  filter(model == "unadjusted") %>%
  arrange(time)

if (nrow(unadj_data) > 0) {
  unadj.plot <- create_survival_plot(unadj_data, "unadjusted")
  print(unadj.plot)
  
  ggsave("unadjusted_plot.png", unadj.plot, 
         width = 11, 
         height = 7,
         dpi = 600)
  ggsave("RWD_unadjusted_plot.pdf", unadj.plot, 
         width = 11, 
         height = 7,
         dpi = 600)
  cat("Saved: unadjusted_plot.png and RWD_unadjusted_plot.pdf\n")
}

# IPTW
iptw_data <- surv_summary %>%
  filter(model == "iptw") %>%
  arrange(time)

if (nrow(iptw_data) > 0) {
  iptw.plot <- create_survival_plot(iptw_data, "iptw")
  print(iptw.plot)
  
  ggsave("iptw_plot.png", iptw.plot, 
         width = 11, 
         height = 7,
         dpi = 600)
  ggsave("RWD_iptw_plot.pdf", iptw.plot, 
         width = 11, 
         height = 7,
         dpi = 600)
  cat("Saved: iptw_plot.png and RWD_iptw_plot.pdf\n")
}

# IPCW
ipcw_data <- surv_summary %>%
  filter(model == "ipcw") %>%
  arrange(time)

if (nrow(ipcw_data) > 0) {
  ipcw.plot <- create_survival_plot(ipcw_data, "ipcw")
  print(ipcw.plot)
  
  ggsave("ipcw_plot.png", ipcw.plot, 
         width = 11, 
         height = 7,
         dpi = 600)
  ggsave("RWD_ipcw_plot.pdf", ipcw.plot, 
         width = 11, 
         height = 7,
         dpi = 600)
  cat("Saved: ipcw_plot.png and RWD_ipcw_plot.pdf\n")
}

# COMBINED
comb_data <- surv_summary %>%
  filter(model == "combined") %>%
  arrange(time)

if (nrow(comb_data) > 0) {
  comb.plot <- create_survival_plot(comb_data, "combined")
  print(comb.plot)
  
  ggsave("comb_plot.png", comb.plot, 
         width = 11, 
         height = 7,
         dpi = 600)
  ggsave("RWD_comb_plot.pdf", comb.plot, 
         width = 11, 
         height = 7,
         dpi = 600)
  cat("Saved: comb_plot.png and RWD_comb_plot.pdf\n")
}

cat("\nAll survival curve plots have been generated and saved.\n")
