library("dplyr")
library("survival")

# Load bootstrap RMST summary
# This file is generated by bootstrap_noreplace.R
output_dir <- "bootstrap_results"  # Update this to match your bootstrap output directory
rmst_summary_file <- file.path(output_dir, "bootstrap_rmst_summary.csv")

if (!file.exists(rmst_summary_file)) {
  stop(sprintf("RMST summary file not found: %s\nPlease run bootstrap_noreplace.R first.", rmst_summary_file))
}

rmst_bootstrap <- read.csv(rmst_summary_file)

# RMST restriction time (should match bootstrap_noreplace.R)
tau <- 2500

# Helper function to compute RMST from survfit object
# (matches the function from bootstrap_noreplace.R)
compute_rmst_from_survfit <- function(survfit_obj, tau) {
  tryCatch({
    # Extract summary with full time grid
    surv_summary <- summary(survfit_obj, extend = TRUE)
    
    # Identify strata labels
    strata_names <- unique(surv_summary$strata)
    if (length(strata_names) != 2) {
      return(list(rmst0 = NA, rmst1 = NA, rmst_diff = NA))
    }
    
    # Helper: extract time and survival for one stratum
    extract_group_data <- function(group_label_pattern) {
      # Find matching strata
      matching_strata <- grep(group_label_pattern, strata_names, value = TRUE)
      if (length(matching_strata) == 0) {
        # Try alternative: use strata order
        ordered_strata <- unique(surv_summary$strata)
        if (group_label_pattern == "=0") {
          matching_strata <- ordered_strata[1]
        } else if (group_label_pattern == "=1") {
          matching_strata <- ordered_strata[2]
        } else {
          return(list(time = numeric(0), surv = numeric(0)))
        }
      }
      idx <- which(surv_summary$strata == matching_strata[1])
      time <- surv_summary$time[idx]
      surv <- surv_summary$surv[idx]
      return(list(time = time, surv = surv))
    }
    
    # Compute RMST manually
    compute_rmst <- function(time, surv, tau) {
      idx <- which(time <= tau)
      if (length(idx) == 0) {
        return(0)  # No events before tau
      }
      time_trunc <- c(0, time[idx], tau)
      surv_trunc <- c(1, surv[idx], surv[max(idx)])
      sum(diff(time_trunc) * head(surv_trunc, -1))
    }
    
    # Extract and compute RMST for both groups
    group0 <- extract_group_data("=0")
    group1 <- extract_group_data("=1")
    
    rmst0 <- compute_rmst(group0$time, group0$surv, tau)
    rmst1 <- compute_rmst(group1$time, group1$surv, tau)
    
    return(list(rmst0 = rmst0, rmst1 = rmst1, rmst_diff = rmst1 - rmst0))
  }, error = function(e) {
    return(list(rmst0 = NA, rmst1 = NA, rmst_diff = NA))
  })
}

# Check if outcomes_df.long exists (should be created by find_kZ_script.R)
# If not, try to source weights_script.R which should have it
if (!exists("outcomes_df.long")) {
  # Try to source weights_script.R to get the point estimate models
  # Note: This assumes find_kZ_script.R has been run first
  if (file.exists("weights_script.R")) {
    source("weights_script.R")
  } else {
    stop("outcomes_df.long not found in environment and weights_script.R not found.\nPlease run find_kZ_script.R and weights_script.R first.")
  }
}

# Get point estimate RMST from weights_script.R models
# These will replace the bootstrap means

# UNADJUSTED
unadj_fit <- survfit(Surv(Tstart, time, ami) ~ treatment, 
                     data = outcomes_df.long, 
                     id = rowId)
unadj_rmst <- compute_rmst_from_survfit(unadj_fit, tau)

# IPTW
iptw_fit <- survfit(Surv(Tstart, time, ami) ~ treatment, 
                    data = outcomes_df.long, 
                    id = rowId, 
                    weights = iptw_trunc)
iptw_rmst <- compute_rmst_from_survfit(iptw_fit, tau)

# IPCW (using Stab_ipcw_trunc as in weights_script.R)
ipcw_fit <- survfit(Surv(Tstart, time, ami) ~ treatment, 
                    data = outcomes_df.long, 
                    id = rowId, 
                    weights = Stab_ipcw_trunc)
ipcw_rmst <- compute_rmst_from_survfit(ipcw_fit, tau)

# COMBINED
comb_fit <- survfit(Surv(Tstart, time, ami) ~ treatment, 
                    data = outcomes_df.long, 
                    id = rowId, 
                    weights = comb)
comb_rmst <- compute_rmst_from_survfit(comb_fit, tau)

# Create point estimate data
point_estimates <- list(
  unadjusted = unadj_rmst,
  iptw = iptw_rmst,
  ipcw = ipcw_rmst,
  combined = comb_rmst
)

# Match bootstrap results with point estimates by Model name
# Replace bootstrap means (_mean columns) with point estimates, keep bootstrap CIs
rmst_df <- rmst_bootstrap %>%
  mutate(
    # RMST for treatment 0 (ACEi) - replace bootstrap mean with point estimate
    RMST0_estimate = case_when(
      Model == "unadjusted" ~ point_estimates$unadjusted$rmst0,
      Model == "iptw" ~ point_estimates$iptw$rmst0,
      Model == "ipcw" ~ point_estimates$ipcw$rmst0,
      Model == "combined" ~ point_estimates$combined$rmst0,
      TRUE ~ NA_real_
    ),
    # RMST for treatment 1 (Thiazide) - replace bootstrap mean with point estimate
    RMST1_estimate = case_when(
      Model == "unadjusted" ~ point_estimates$unadjusted$rmst1,
      Model == "iptw" ~ point_estimates$iptw$rmst1,
      Model == "ipcw" ~ point_estimates$ipcw$rmst1,
      Model == "combined" ~ point_estimates$combined$rmst1,
      TRUE ~ NA_real_
    ),
    # RMST difference (Thiazide - ACEi) - replace bootstrap mean with point estimate
    RMST_diff_estimate = case_when(
      Model == "unadjusted" ~ point_estimates$unadjusted$rmst_diff,
      Model == "iptw" ~ point_estimates$iptw$rmst_diff,
      Model == "ipcw" ~ point_estimates$ipcw$rmst_diff,
      Model == "combined" ~ point_estimates$combined$rmst_diff,
      TRUE ~ NA_real_
    ),
    # Add tau
    tau = tau
  ) %>%
  # Reorder columns for clarity: remove _mean columns, keep CIs
  select(Model, 
         RMST0_estimate, RMST0_CI_lower, RMST0_CI_upper,
         RMST1_estimate, RMST1_CI_lower, RMST1_CI_upper,
         RMST_diff_estimate, RMST_diff_CI_lower, RMST_diff_CI_upper,
         n_valid, tau)

# Print the dataframe
cat("\n=== RMST Results: Point Estimates with Bootstrap Confidence Intervals ===\n")
cat(sprintf("Restriction time (tau): %d days\n\n", tau))
print(rmst_df)

# Save to CSV
output_file <- "rmst_point_est_with_bootstrap_ci.csv"
write.csv(rmst_df, output_file, row.names = FALSE)
cat(sprintf("\nRMST results saved to: %s\n", output_file))

# Also create a more formatted version for presentation
rmst_formatted <- rmst_df %>%
  mutate(
    RMST0 = sprintf("%.2f (%.2f, %.2f)", RMST0_estimate, RMST0_CI_lower, RMST0_CI_upper),
    RMST1 = sprintf("%.2f (%.2f, %.2f)", RMST1_estimate, RMST1_CI_lower, RMST1_CI_upper),
    RMST_diff = sprintf("%.2f (%.2f, %.2f)", RMST_diff_estimate, RMST_diff_CI_lower, RMST_diff_CI_upper)
  ) %>%
  select(Model, RMST0, RMST1, RMST_diff, n_valid, tau)

cat("\n=== Formatted RMST Results ===\n")
print(rmst_formatted)

formatted_file <- "rmst_point_est_with_bootstrap_ci_formatted.csv"
write.csv(rmst_formatted, formatted_file, row.names = FALSE)
cat(sprintf("Formatted RMST results saved to: %s\n", formatted_file))

cat("\nDone!\n")
